# Generated by Django 5.1.7 on 2025-04-28 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_articles_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
