# Generated by Django 5.1.7 on 2025-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_articleimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
