# Generated by Django 5.1.7 on 2025-04-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
