# Generated by Django 5.1.7 on 2025-04-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
