# Generated by Django 5.1.7 on 2025-04-28 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
