# Generated by Django 5.1.7 on 2025-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
