# Generated by Django 5.1.7 on 2025-06-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_postimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
